name: BurgerMoon Views
favicon: null
layout_spectrum: 0.78811
typography_spectrum: 0.24037
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010800'
    - '#3cd5fe'
    - '#618291'
    - '#ef33a3'
  brandStrength: 0.6875
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
